// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgkgdkpjofvwxdqhfpjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1na2dka3Bqb2Z2d3hkcWhmcGp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDM3MjksImV4cCI6MjA3MzExOTcyOX0.9ztSTm-mvEE4SOTGsXAw54aFFdcNXAnBkj0wvkpsWyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});